services:
  nestjs:
    build: ./nestjs
    volumes:
      - ./nestjs:/app
    working_dir: /app
    ports:
      - '3000:3000'
    command: "npm i --dev && npm run start:dev"

  # adapted from https://medium.com/@bnay14/shipping-docker-logs-to-amazon-s3-using-fluent-bit-9375eb7225ee
  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluentbit/aws-credentials:/root/.aws/credentials
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/parser.conf:/fluent-bit/etc/parser.conf
      - ./fluentbit/formatter.lua:/fluent-bit/etc/formatter.lua
    command: fluent-bit -c /fluent-bit/etc/fluent-bit.conf  
    depends_on:
      - minio

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root
      - MINIO_ROOT_PASSWORD=minio-root
      - MINIO_DEFAULT_BUCKETS=container-logs
    volumes:
      - minio-volume:/bitnami/minio/data

        #   clickhouse:
        #     # we used bitnami's image as they provided easier configuration for experimental purposes
        #     image: bitnami/clickhouse:latest
        #     environment:
        #       # the default user is username 'default' and password 'nil'
        #       - ALLOW_EMPTY_PASSWORD=no
        #       - CLICKHOUSE_ADMIN_PASSWORD=clickhouse-root
        #     volumes:
        #       - clickhouse-volume:/bitnami/clickhouse
        # 
        #   # container for running load tester
        #   tester:
        #     build: ./tester
        #     volumes:
        #       - ./tester:/app
        #     working_dir: /app
        #     command: tail -f /dev/null
        #     # resource limitation definitions. reference: https://docs.docker.com/compose/compose-file/deploy/#resources
        #     deploy:
        #       resources:
        #         limits:
        #           cpus: '2'
        #           memory: 1G

volumes:
  postgres-db-volume:
  clickhouse-volume:
  minio-volume:
